# Setup
title: TLDR Blog
tagline: tech, git, computer science, blog, tmux, vim
url: https://b3z.github.io
paginate: 1
baseurl: ""
about: "about"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: b3z
  url: https://github.com/b3z
  email: b3z@zeppel.eu

# Custom vars
version: 3.0.0
